chain_client:
  # 链ID
  chain_id: "medicineTest"
  # 组织ID
  org_id: "TestCMorg1"
  # 客户端用户私钥路径
  user_key_file_path: "/root/chain/release/TestCMorg1-示例测试节点1/config/TestCMorg1/certs/user/示例测试用户1/示例测试用户1.tls.key"
  # 客户端用户证书路径
  user_crt_file_path: "/root/chain/release/TestCMorg1-示例测试节点1/config/TestCMorg1/certs/user/示例测试用户1/示例测试用户1.tls.crt"
  # 客户端用户交易签名私钥路径(若未设置，将使用user_key_file_path)
  user_sign_key_file_path: "/root/chain/release/TestCMorg1-示例测试节点1/config/TestCMorg1/certs/user/示例测试用户1/示例测试用户1.sign.key"
  # 客户端用户交易签名证书路径(若未设置，将使用user_crt_file_path)
  user_sign_crt_file_path: "/root/chain/release/TestCMorg1-示例测试节点1/config/TestCMorg1/certs/user/示例测试用户1/示例测试用户1.sign.crt"

  retry_limit: 10
  # 同步交易结果模式下，每次轮训交易结果时的等待时间，单位：ms 删除此项或设为<=0则使用默认值 500
  retry_interval: 500
  # 当前签名证书的别名。当设置此配置项时，chain client 对象将自动检查链上是否已添加此别名，如果没有则自动上链此证书别名，
  # 并且后续所有交易都会使用别名，别名可降低交易体大小。若为空则不启用。
  #  alias: mycert5
  nodes:
    - # 节点地址，格式为：IP:端口:连接数
      node_addr: "152.136.182.202:12301"
      # 节点连接数
      conn_cnt: 10
      # RPC连接是否启用双向TLS认证
      enable_tls: true
      # 信任证书池路径
      trust_root_paths:
        - "/root/chain/release/TestCMorg1-示例测试节点1/config/TestCMorg1/certs/ca/TestCMorg1"
      # TLS hostname
      tls_host_name: "chainmaker.org"
    - # 节点地址，格式为：IP:端口:连接数
      node_addr: "152.136.182.202:12302"
      # 节点连接数
      conn_cnt: 10
      # RPC连接是否启用双向TLS认证
      enable_tls: true
      # 信任证书池路径
      trust_root_paths:
        - "/root/chain/release/TestCMorg1-示例测试节点1/config/TestCMorg1/certs/ca/TestCMorg2"
      # TLS hostname
      tls_host_name: "chainmaker.org"
    - # 节点地址，格式为：IP:端口:连接数
      node_addr: "152.136.182.202:12303"
      # 节点连接数
      conn_cnt: 10
      # RPC连接是否启用双向TLS认证
      enable_tls: true
      # 信任证书池路径
      trust_root_paths:
        - "/root/chain/release/TestCMorg1-示例测试节点1/config/TestCMorg1/certs/ca/TestCMorg3"
      # TLS hostname
      tls_host_name: "chainmaker.org"
    - # 节点地址，格式为：IP:端口:连接数
      node_addr: "152.136.182.202:12304"
      # 节点连接数
      conn_cnt: 10
      # RPC连接是否启用双向TLS认证
      enable_tls: true
      # 信任证书池路径
      trust_root_paths:
        - "/root/chain/release/TestCMorg1-示例测试节点1/config/TestCMorg1/certs/ca/TestCMorg4"
      # TLS hostname
      tls_host_name: "chainmaker.org"
  archive:
    # 数据归档链外存储相关配置
    type: "mysql"
    dest: "root:123456:localhost:3306"
    secret_key: xxx
  rpc_client:
    # grpc客户端最大接受容量(MB)
    max_receive_message_size: 16